name: Test Automation Workflow

on:
  schedule:
  - cron: 30 14 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation framework with Maven
      run:  mvn test -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=true -X

    - name: Upload test logs
      if: always()
      uses: actions/upload-artifact@v4.6.0
      with: 
        name: Test Logs
        path: logs/

    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v4.6.0
      with: 
        name: screenshots
        path: screenshots/

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4.6.0
      with: 
        name: Test Reports
        path: report.html
        
    - name: Test Execution status
      run: echo "Test Execution Completed"

    - name: Copy Report to gh-pages folder
      if: always()

      run: |
        mkdir -p public/extent-reports
        cp -R report.html public/extent-reports/
        cp -R screenshots/ public/screenshots
        ls -l
        
    - name: Deploy
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public/extent-reports/
        token: ${{ secrets.AUT88 }}
        clean: true
